name: Coverage

on:
  push:
    branches: [ master, coverage ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ master, coverage ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential cmake python3-pip pybind11-dev libeigen3-dev libfmt-dev libtbb-dev libomp-dev libpcl-dev libgtest-dev lcov
          pip install -U setuptools pytest numpy scipy

      - name: Build (C++)
        run: |
          mkdir build && cd build
          cmake .. -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_BENCHMARKS=ON -DBUILD_WITH_TBB=ON -DBUILD_WITH_PCL=ON -DENABLE_COVERAGE=ON
          cmake --build . -j$(nproc)
      
      - name: Test (C++)
        run: |
          ctest -j$(nproc)

      - name: Build (Python)
        run: |
          cd ..
          python3 setup.py build && python3 setup.py install --user

      - name: Test (Python)
        run: |
          pytest src/example/basic_registration.py
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: koide3/small_gicp
